=== DOCGroup/ACE_TAO/branches/EC_DT_RTAS/TAO/orbsvcs/examples/RtEC/ECConfigurator/ecconfig.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!-- ECCONFIGURATION -->
  <!ELEMENT ECConfiguration ((Event|Timeout)*,(LocalEventChannel|RemoteEventChannel)*,TestDriver) >

<!-- EVENT -->
  <!ELEMENT Event (Period,Phase,Criticality,Importance,WorstExecution,TypicalExecution) >
  <!ATTLIST Event name CDATA #REQUIRED >
  <!ATTLIST Event type CDATA #REQUIRED >

  <!ELEMENT Criticality (EMPTY) >
  <!ATTLIST Criticality value (VERY_LOW|LOW|MEDIUM|HIGH|VERY_HIGH) #REQUIRED >

  <!ELEMENT Importance (EMPTY) >
  <!ATTLIST Importance value (VERY_LOW|LOW|MEDIUM|HIGH|VERY_HIGH) #REQUIRED >

  <!ELEMENT WorstExecution (#PCDATA) >

  <!ELEMENT TypicalExecution (#PCDATA) >

<!-- TIMEOUT -->
  <!ELEMENT Timeout (Period,Phase?) >
  <!ATTLIST Timeout name CDATA #REQUIRED >

  <!ELEMENT Period (#PCDATA) >

  <!ELEMENT Phase (#PCDATA) >

<!-- LOCALEVENTCHANNEL -->
  <!ELEMENT LocalEventChannel (SchedulingStrategy,(Consumer,Supplier)*) >
  <!ATTLIST LocalEventChannel name CDATA #REQUIRED >

  <!ELEMENT SchedulingStrategy (EMPTY) >
  <!ATTLIST SchedulingStrategy type (EDF|MUF|RMS) #REQUIRED >
  <!ATTLIST SchedulingStrategy enableRG (yes|no) #REQUIRED >

  <!ELEMENT Consumer (Subscriptions,Dependants?) >
  <!ATTLIST Consumer name CDATA #REQUIRED >

  <!ELEMENT Subscriptions (EventName*) >

  <!ELEMENT EventName (#PCDATA) >

  <!ELEMENT Dependants (SupplierName*) >

  <!ELEMENT SupplierName (#PCDATA) >

  <!-- If no Triggers is supplied (or it is empty), the Supplier is assumed to be self-triggered -->
  <!ELEMENT Supplier (Publications,Triggers?) >
  <!ATTLIST Supplier name CDATA #REQUIRED >
  <!ATTLIST Supplier id CDATA #REQUIRED >

  <!ELEMENT Publications (EventName*) >

  <!ELEMENT Triggers (TimeoutName*) >

  <!ELEMENT TimeoutName (#PCDATA) >

<!-- REMOTEEVENTCHANNEL -->
  <!-- Consumer/Supplier on remote are local but subscribe/publish remotely -->
  <!ELEMENT RemoteEventChannel (IORFile, (Consumer,Supplier)*) >
  <!ATTLIST RemoteEventChannel name CDATA #REQUIRED >

  <!ELEMENT IORFile (#PCDATA) >

<!-- There should only be one Driver for each process-->
<!-- TESTDRIVER -->
  <!ELEMENT TestDriver (StartCondition,StopCondition) >

  <!ELEMENT StartCondition (Time) >
  <!ATTLIST StartCondition type (GlobalTime|DelayAfterStart|DelayAfterConnect) #REQUIRED >
  <!ATTLIST StartCondition master (yes|no) "no" >

  <!ELEMENT Time (#PCDATA) >

  <!ELEMENT StopCondition (Value) >
  <!ATTLIST StopCondition type (Duration|EventNumber) #REQUIRED >

  <!ELEMENT Value (#PCDATA) >

=== DOCGroup/ACE_TAO/branches/EC_DT_RTAS/TAO/orbsvcs/examples/RtEC/ECConfigurator/chain_test/conssuppec.xml
<?xml version="1.0"?>
<!DOCTYPE ECConfiguration SYSTEM "ecconfig.dtd">

<ECConfiguration>
    
<!-- Define the events -->
<Event name="Subtask2 Trigger" type="17">
  <Period>200</Period> <!-- in msec -->
  <Phase>0</Phase> <!-- in msec -->
  <Criticality value="VERY_LOW" />
  <Importance value="VERY_LOW" />
  <WorstExecution>50</WorstExecution> <!-- in msec -->
  <TypicalExecution>50</TypicalExecution> <!-- in msec -->
</Event>

<Event name="Subtask3 Trigger" type="18">
  <Period>200</Period> <!-- in msec -->
  <Phase>0</Phase> <!-- in msec -->
  <Criticality value="VERY_HIGH" />
  <Importance value="VERY_HIGH" />
  <WorstExecution>50</WorstExecution> <!-- in msec -->
  <TypicalExecution>50</TypicalExecution> <!-- in msec -->
</Event>

<!-- Configure the ECs -->
<RemoteEventChannel name="Client" connection="Output">
  <IORFile>Client.ior</IORFile>
</RemoteEventChannel>
<RemoteEventChannel name="Server" connection="Input">
  <IORFile>Server.ior</IORFile>
</RemoteEventChannel>

<LocalEventChannel name="Middle" >
  <SchedulingStrategy type="EDF" enableRG="true" />
  <Supplier name="Subtask3 Notifier" id="3">
    <Publications>
      <EventName>Subtask3 Trigger</EventName>
    </Publications>
  </Supplier>
  <Consumer name="Subtask2 Executor" >
    <Subscriptions>
      <EventName>Subtask2 Trigger</EventName>
    </Subscriptions>
    <Dependants>
      <SupplierName>Subtask3 Notifier</SupplierName>
    </Dependants>
  </Consumer>
</LocalEventChannel>

<!-- Configure the driver -->
<TestDriver>
  <StartCondition type="DelayAfterConnect" >
    <Time>10000</Time> <!-- in msecs -->
  </StartCondition>
  <StopCondition type="Duration" >
    <Value>340000</Value> <!-- duration in msecs -->
  </StopCondition>
</TestDriver>

</ECConfiguration>
