=== DOCGroup/ACE_TAO/branches/TAO_Iterators_Updated/CIAO/docs/schema/Task_Map.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.vanderbilt.edu/SA-POP Task_Map.xsd" xmlns:SA-POP="http://www.vanderbilt.edu/SA-POP"
  targetNamespace="http://www.vanderbilt.edu/SA-POP" elementFormDefault="qualified">
  <!-- Simple types. -->
  <xs:simpleType name="TaskID">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="1" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="TaskImplID">
    <xs:restriction base="xs:string" />
  </xs:simpleType>
  <xs:simpleType name="ResourceID">
    <xs:restriction base="xs:string" />
  </xs:simpleType>
  <xs:simpleType name="ResourceKind">
    <xs:restriction base="xs:string">
      <xs:enumeration value="UNARY" />
      <xs:enumeration value="DISCRETE" />
      <xs:enumeration value="RESERVOIR" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ResourceValue">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="0" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ImplParamID">
    <xs:restriction base="xs:string" />
  </xs:simpleType>
  <xs:simpleType name="ImplParamKind">
    <xs:restriction base="xs:string" />
  </xs:simpleType>
  <xs:simpleType name="ImplParamValue">
    <xs:restriction base="xs:string" />
  </xs:simpleType>
  <xs:simpleType name="TimeValue">
    <xs:restriction base="xs:int">
      <!-- -1 indicates unknown/unconstrained time -->
      <xs:minInclusive value="-1" />
    </xs:restriction>
  </xs:simpleType>
  <!-- Complex types corresponding to IDL structures.
       (resources, parameters, implementations, associations, and task map) -->
  <xs:complexType name="Resource">
    <xs:sequence>
      <xs:element name="resourceID" type="SA-POP:ResourceID" />
      <xs:element name="kind" type="SA-POP:ResourceKind" default="DISCRETE" />
      <xs:element name="capacity" type="SA-POP:ResourceValue" default="100" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ImplParam">
    <xs:sequence>
      <xs:element name="paramID" type="SA-POP:ImplParamID" />
      <xs:element name="kind" type="SA-POP:ImplParamKind" />
      <xs:element name="value" type="SA-POP:ImplParamValue" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TaskImpl">
    <xs:sequence>
      <xs:element name="implID" type="SA-POP:TaskImplID" />
      <xs:element name="param" type="SA-POP:ImplParam" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TaskToImpl">
    <xs:sequence>
      <xs:element name="taskID" type="SA-POP:TaskID" />
      <xs:element name="implID" type="SA-POP:TaskImplID" />
      <xs:element name="duration" type="SA-POP:TimeValue" default="-1" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ImplToResource">
    <xs:sequence>
      <xs:element name="implID" type="SA-POP:TaskImplID" />
      <xs:element name="resourceID" type="SA-POP:ResourceID" />
      <xs:element name="utilization" type="SA-POP:ResourceValue" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TaskMap">
    <xs:sequence>
      <xs:element name="taskImpl" type="SA-POP:TaskImpl" maxOccurs="unbounded" />
      <xs:element name="resource" type="SA-POP:Resource" maxOccurs="unbounded" />
      <xs:element name="taskToImpl" type="SA-POP:TaskToImpl" maxOccurs="unbounded" />
      <xs:element name="implToResource" type="SA-POP:ImplToResource" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <!-- Top-level task map element. -->
  <xs:element name="taskMap" type="SA-POP:TaskMap"></xs:element>
</xs:schema>

=== DOCGroup/ACE_TAO/branches/SAPOP_Threat_dev/C2W/c2w.tm.xml
<?xml version="1.0" encoding="utf-8" ?>
<SA-POP:taskMap
  xmlns:SA-POP="http://www.vanderbilt.edu/SA-POP"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.vanderbilt.edu/SA-POP Task_Map.xsd"
  xmlns="http://www.vanderbilt.edu/SA-POP">

  <taskImpl>
    <implID>SIGINT_CALL</implID>
    <param>
      <paramID>test_param1</paramID>
      <kind>test_param_kind1</kind>
      <value>test_param_value1</value>
    </param>
  </taskImpl>
  <taskImpl>
    <implID>CAOC_COORD</implID>
    <param>
      <paramID>test_param1</paramID>
      <kind>test_param_kind1</kind>
      <value>test_param_value1</value>
    </param>
  </taskImpl>
  <taskImpl>
    <implID>UAV_LOCATE</implID>
    <param>
      <paramID>test_param1</paramID>
      <kind>test_param_kind1</kind>
      <value>test_param_value1</value>
    </param>
  </taskImpl>
  <taskImpl>
    <implID>UAV_LOCK</implID>
    <param>
      <paramID>test_param1</paramID>
      <kind>test_param_kind1</kind>
      <value>test_param_value1</value>
    </param>
  </taskImpl>
  <taskImpl>
    <implID>UAV_FIND_NEIGH</implID>
    <param>
      <paramID>test_param1</paramID>
      <kind>test_param_kind1</kind>
      <value>test_param_value1</value>
    </param>
  </taskImpl>
  <taskImpl>
    <implID>UAV_EXAMINE</implID>
    <param>
      <paramID>test_param1</paramID>
      <kind>test_param_kind1</kind>
      <value>test_param_value1</value>
    </param>
  </taskImpl>
  <taskImpl>
    <implID>UAV_ARMED</implID>
    <param>
      <paramID>test_param1</paramID>
      <kind>test_param_kind1</kind>
      <value>test_param_value1</value>
    </param>
  </taskImpl>
  <taskImpl>
    <implID>UAV_FIRE</implID>
    <param>
      <paramID>test_param1</paramID>
      <kind>test_param_kind1</kind>
      <value>test_param_value1</value>
    </param>
  </taskImpl>
  <taskImpl>
    <implID>UAV_ASSESS</implID>
    <param>
      <paramID>test_param1</paramID>
      <kind>test_param_kind1</kind>
      <value>test_param_value1</value>
    </param>
  </taskImpl>
  <taskImpl>
    <implID>CAOC_APPROVAL</implID>
    <param>
      <paramID>test_param1</paramID>
      <kind>test_param_kind1</kind>
      <value>test_param_value1</value>
    </param>
  </taskImpl>
  <taskImpl>
    <implID>GROUND_PREPARE</implID>
    <param>
      <paramID>test_param1</paramID>
      <kind>test_param_kind1</kind>
      <value>test_param_value1</value>
    </param>
  </taskImpl>
  <taskImpl>
    <implID>CAOC_SET</implID>
    <param>
      <paramID>test_param1</paramID>
      <kind>test_param_kind1</kind>
      <value>test_param_value1</value>
    </param>
  </taskImpl>
  <taskImpl>
    <implID>GROUND_SEIZE</implID>
    <param>
      <paramID>test_param1</paramID>
      <kind>test_param_kind1</kind>
      <value>test_param_value1</value>
    </param>
  </taskImpl>
    
    
  <resource>
    <resourceID>Vehicles</resourceID>
    <kind>DISCRETE</kind>
    <capacity>2</capacity>
  </resource>
  <resource>
    <resourceID>Troops</resourceID>
    <kind>DISCRETE</kind>
    <capacity>1</capacity>
  </resource>
  <resource>
    <resourceID>Intel</resourceID>
    <kind>DISCRETE</kind>
    <capacity>1</capacity>
  </resource>
    

  <taskToImpl>
    <taskID>1001</taskID>
    <implID>SIGINT_CALL</implID>
    <duration>10</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>1002</taskID>
    <implID>CAOC_COORD</implID>
    <duration>10</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>1003</taskID>
    <implID>UAV_LOCATE</implID>
    <duration>10</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>1004</taskID>
    <implID>UAV_LOCK</implID>
    <duration>10</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>1005</taskID>
    <implID>UAV_FIND_NEIGH</implID>
    <duration>10</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>1006</taskID>
    <implID>UAV_EXAMINE</implID>
    <duration>10</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>1007</taskID>
    <implID>UAV_ARMED</implID>
    <duration>5</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>1013</taskID>
    <implID>CAOC_APPROVAL</implID>
    <duration>10</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>1008</taskID>
    <implID>UAV_FIRE</implID>
    <duration>2</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>1009</taskID>
    <implID>UAV_ASSESS</implID>
    <duration>10</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>1010</taskID>
    <implID>GROUND_PREPARE</implID>
    <duration>10</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>1011</taskID>
    <implID>CAOC_SET</implID>
    <duration>10</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>1012</taskID>
    <implID>GROUND_SEIZE</implID>
    <duration>10</duration>
  </taskToImpl>

  <implToResource>
    <implID>SIGINT_CALL</implID>
    <resourceID>Intel</resourceID>
    <utilization>1</utilization>
  </implToResource>
  <implToResource>
    <implID>CAOC_COORD</implID>
    <resourceID>Intel</resourceID>
    <utilization>1</utilization>
  </implToResource>
  <implToResource>
    <implID>UAV_LOCATE</implID>
    <resourceID>Vehicles</resourceID>
    <utilization>1</utilization>
  </implToResource>
  <implToResource>
    <implID>UAV_LOCK</implID>
    <resourceID>Vehicles</resourceID>
    <utilization>1</utilization>
  </implToResource>
  <implToResource>
    <implID>UAV_FIND_NEIGH</implID>
    <resourceID>Vehicles</resourceID>
    <utilization>1</utilization>
  </implToResource>
  <implToResource>
    <implID>UAV_EXAMINE</implID>
    <resourceID>Vehicles</resourceID>
    <utilization>1</utilization>
  </implToResource>
  <implToResource>
    <implID>UAV_ARMED</implID>
    <resourceID>Vehicles</resourceID>
    <utilization>1</utilization>
  </implToResource>
  <implToResource>
    <implID>CAOC_APPROVAL</implID>
    <resourceID>Intel</resourceID>
    <utilization>1</utilization>
  </implToResource>
  <implToResource>
    <implID>UAV_FIRE</implID>
    <resourceID>Vehicles</resourceID>
    <utilization>1</utilization>
  </implToResource>
  <implToResource>
    <implID>UAV_ASSESS</implID>
    <resourceID>Vehicles</resourceID>
    <utilization>1</utilization>
  </implToResource>
  <implToResource>
    <implID>CAOC_SET</implID>
    <resourceID>Intel</resourceID>
    <utilization>1</utilization>
  </implToResource>
  <implToResource>
    <implID>GROUND_PREPARE</implID>
    <resourceID>Troops</resourceID>
    <utilization>1</utilization>
  </implToResource>
  <implToResource>
    <implID>GROUND_SEIZE</implID>
    <resourceID>Troops</resourceID>
    <utilization>1</utilization>
  </implToResource>


</SA-POP:taskMap>

=== DOCGroup/ACE_TAO/branches/RACE_devl/SA_POP/examples/Scheduling/sched_main_test.tm.xml
<?xml version="1.0" encoding="utf-8" ?>
<SA-POP:taskMap xmlns:SA-POP="http://www.vanderbilt.edu/SA-POP" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.vanderbilt.edu/SA-POP Task_Map.xsd" xmlns="http://www.vanderbilt.edu/SA-POP">
  <taskImpl>
    <implID>_ABFC1EAC-BA43-4F33-969C-72DF5F15310A1</implID>
    <param>
      <paramID></paramID>
      <kind></kind>
      <value></value>
    </param>
  </taskImpl>
  <taskImpl>
    <implID>_6F72C45B-C490-4D1F-B79B-744489E16C7E2</implID>
    <param>
      <paramID></paramID>
      <kind></kind>
      <value></value>
    </param>
  </taskImpl>
  <taskImpl>
    <implID>_8E619279-F191-495B-86D9-8813967D73EB3</implID>
    <param>
      <paramID></paramID>
      <kind></kind>
      <value></value>
    </param>
  </taskImpl>
  <taskImpl>
    <implID>_47EB0690-2A1B-42F6-AA60-B901814E884E4</implID>
    <param>
      <paramID></paramID>
      <kind></kind>
      <value></value>
    </param>
  </taskImpl>
  <taskImpl>
    <implID>_A622DD4F-F709-479E-AEC6-80680D6B543D5</implID>
    <param>
      <paramID></paramID>
      <kind></kind>
      <value></value>
    </param>
  </taskImpl>
  <taskImpl>
    <implID>_864725F9-CBB2-462E-85F2-CE44C668A39E6</implID>
    <param>
      <paramID></paramID>
      <kind></kind>
      <value></value>
    </param>
  </taskImpl>
  <taskImpl>
    <implID>_DB70C55B-3312-4279-9354-73B0DF98DAAA7</implID>
    <param>
      <paramID></paramID>
      <kind></kind>
      <value></value>
    </param>
  </taskImpl>
  <taskImpl>
    <implID>_7CB380A7-8BCD-44C5-8D12-63AD69D753BD8</implID>
    <param>
      <paramID></paramID>
      <kind></kind>
      <value></value>
    </param>
  </taskImpl>
  <taskImpl>
    <implID>_7CB380A7-8BCD-44C5-8D12-63AD69D753CE9</implID>
    <param>
      <paramID></paramID>
      <kind></kind>
      <value></value>
    </param>
  </taskImpl>
  <taskImpl>
    <implID>_7CB380A7-8BCD-44C5-8D12-63AD69D753C10</implID>
    <param>
      <paramID></paramID>
      <kind></kind>
      <value></value>
    </param>
  </taskImpl>
  <resource>
    <resourceID>MEMORY</resourceID>
    <kind>DISCRETE</kind>
    <capacity>15</capacity>
  </resource>
  <taskToImpl>
    <taskID>201</taskID>
    <implID>_ABFC1EAC-BA43-4F33-969C-72DF5F15310A1</implID>
    <duration>6</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>202</taskID>
    <implID>_ABFC1EAC-BA43-4F33-969C-72DF5F15310A1</implID>
    <duration>6</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>203</taskID>
    <implID>_ABFC1EAC-BA43-4F33-969C-72DF5F15310A1</implID>
    <duration>6</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>204</taskID>
    <implID>_ABFC1EAC-BA43-4F33-969C-72DF5F15310A1</implID>
    <duration>6</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>211</taskID>
    <implID>_6F72C45B-C490-4D1F-B79B-744489E16C7E2</implID>
    <duration>0</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>212</taskID>
    <implID>_6F72C45B-C490-4D1F-B79B-744489E16C7E2</implID>
    <duration>0</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>213</taskID>
    <implID>_6F72C45B-C490-4D1F-B79B-744489E16C7E2</implID>
    <duration>0</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>214</taskID>
    <implID>_6F72C45B-C490-4D1F-B79B-744489E16C7E2</implID>
    <duration>0</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>221</taskID>
    <implID>_8E619279-F191-495B-86D9-8813967D73EB3</implID>
    <duration>0</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>222</taskID>
    <implID>_8E619279-F191-495B-86D9-8813967D73EB3</implID>
    <duration>0</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>281</taskID>
    <implID>_47EB0690-2A1B-42F6-AA60-B901814E884E4</implID>
    <duration>0</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>282</taskID>
    <implID>_47EB0690-2A1B-42F6-AA60-B901814E884E4</implID>
    <duration>0</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>241</taskID>
    <implID>_A622DD4F-F709-479E-AEC6-80680D6B543D5</implID>
    <duration>0</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>241</taskID>
    <implID>_7CB380A7-8BCD-44C5-8D12-63AD69D753C10</implID>
    <duration>0</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>242</taskID>
    <implID>_A622DD4F-F709-479E-AEC6-80680D6B543D5</implID>
    <duration>0</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>231</taskID>
    <implID>_864725F9-CBB2-462E-85F2-CE44C668A39E6</implID>
    <duration>0</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>251</taskID>
    <implID>_DB70C55B-3312-4279-9354-73B0DF98DAAA7</implID>
    <duration>0</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>252</taskID>
    <implID>_DB70C55B-3312-4279-9354-73B0DF98DAAA7</implID>
    <duration>0</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>261</taskID>
    <implID>_7CB380A7-8BCD-44C5-8D12-63AD69D753BD8</implID>
    <duration>0</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>262</taskID>
    <implID>_7CB380A7-8BCD-44C5-8D12-63AD69D753BD8</implID>
    <duration>0</duration>
  </taskToImpl>
  <taskToImpl>
    <taskID>271</taskID>
    <implID>_7CB380A7-8BCD-44C5-8D12-63AD69D753CE9</implID>
    <duration>0</duration>
  </taskToImpl>
  <implToResource>
    <implID>_ABFC1EAC-BA43-4F33-969C-72DF5F15310A1</implID>
    <resourceID>MEMORY</resourceID>
    <utilization>1</utilization>
  </implToResource>
  <implToResource>
    <implID>_6F72C45B-C490-4D1F-B79B-744489E16C7E2</implID>
    <resourceID>MEMORY</resourceID>
    <utilization>3</utilization>
  </implToResource>
  <implToResource>
    <implID>_8E619279-F191-495B-86D9-8813967D73EB3</implID>
    <resourceID>MEMORY</resourceID>
    <utilization>1</utilization>
  </implToResource>
  <implToResource>
    <implID>_47EB0690-2A1B-42F6-AA60-B901814E884E4</implID>
    <resourceID>MEMORY</resourceID>
    <utilization>2</utilization>
  </implToResource>
  <implToResource>
    <implID>_A622DD4F-F709-479E-AEC6-80680D6B543D5</implID>
    <resourceID>MEMORY</resourceID>
    <utilization>6</utilization>
  </implToResource>
  <implToResource>
    <implID>_864725F9-CBB2-462E-85F2-CE44C668A39E6</implID>
    <resourceID>MEMORY</resourceID>
    <utilization>3</utilization>
  </implToResource>
  <implToResource>
    <implID>_DB70C55B-3312-4279-9354-73B0DF98DAAA7</implID>
    <resourceID>MEMORY</resourceID>
    <utilization>4</utilization>
  </implToResource>
  <implToResource>
    <implID>_7CB380A7-8BCD-44C5-8D12-63AD69D753BD8</implID>
    <resourceID>MEMORY</resourceID>
    <utilization>1</utilization>
  </implToResource>
  <implToResource>
    <implID>_7CB380A7-8BCD-44C5-8D12-63AD69D753CE9</implID>
    <resourceID>MEMORY</resourceID>
    <utilization>2</utilization>
  </implToResource>
  <implToResource>
    <implID>_7CB380A7-8BCD-44C5-8D12-63AD69D753C10</implID>
    <resourceID>MEMORY</resourceID>
    <utilization>2</utilization>
  </implToResource>
</SA-POP:taskMap>
