<?xml version="1.0"?>
<!DOCTYPE SERVER_REPOSITORY  [
<!ELEMENT SERVER_INFORMATION (Server, Logical_Server*, StartupOptions, Location)>
<!ELEMENT Server (#PCDATA)>
<!ELEMENT Logical_Server (#PCDATA)>
<!ELEMENT StartupOptions (Command_Line, Environment*, Working_Directory*, Activation*, Location)>
<!ELEMENT Command_Line (#PCDATA)>
<!ELEMENT Working_Directory (#PCDATA)>
<!ELEMENT Activation (NORMAL | MANUAL | PER_CLIENT | AUTO_START)>
<!ELEMENT Location (#PCDATA)>
]>

<SERVER_REPOSITORY>

<SERVER_INFORMATION>
<Server>airplane_server</Server>
<StartupOptions>
<Command_Line>./airplane_server</Command_Line>
<Location>doc</Location>
</SERVER_INFORMATION>

</SERVER_REPOSITORY>
