=== DOCGroup/ACE_TAO/branches/Telcordia_Diffserv/CIAO/OLD_RACE2/Planners/ImportanceBinPacker/DeploymentScript.xsd
<?xml version="1.0" encoding="utf-8"?>

<xsd:schema
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns:scr="http://dtsn.darpa.mil/ixo/programs.asp?id=6#/DeploymentScript"
 xsi:schemaLocation="http://www.w3.org/2001/XMLSchema XMLSchema.xsd"
 targetNamespace="http://dtsn.darpa.mil/ixo/programs.asp?id=6#/DeploymentScript"
 >

 <!-- The main body of a script file is the <script> element,
      which can contain any number of
      <shell>, <initialize>, <changeDomain>,
      <deploy>, <teardown>, <change>, or <dump> elements. -->

 <xsd:element name="script">
    <xsd:complexType>
       <xsd:sequence>
          <xsd:choice minOccurs="0" maxOccurs="unbounded">
             <xsd:element name="shell" type="scr:shell"/>
             <xsd:element name="initialize" type="scr:initialize"/>
             <xsd:element name="changeDomain" type="scr:changeDomain"/>
             <xsd:element name="deploy" type="scr:stringList"/>
             <xsd:element name="teardown" type="scr:stringList"/>
             <xsd:element name="change" type="scr:changeStringList"/>
             <xsd:element name="dump" type="scr:dump"/>
          </xsd:choice>
       </xsd:sequence>
    </xsd:complexType>
 </xsd:element>

 <xsd:simpleType name="shell">
    <xsd:restriction base="xsd:string">
       <xsd:whiteSpace value="preserve"/>
    </xsd:restriction>
 </xsd:simpleType>

 <xsd:complexType name="initialize">
    <xsd:sequence>
       <xsd:element name="node"
                    minOccurs="0"
                    maxOccurs="unbounded">
          <xsd:complexType>
             <xsd:attribute name="name" type="xsd:string"/>
             <xsd:attribute name="capacity" type="xsd:integer"/>
          </xsd:complexType>
       </xsd:element>
    </xsd:sequence>
 </xsd:complexType>

 <xsd:complexType name="changeDomain">
    <xsd:sequence>
       <xsd:choice minOccurs="0" maxOccurs="unbounded">
          <xsd:element name="fail" type="xsd:string"/>
          <xsd:element name="join" type="xsd:string"/>
          <xsd:element name="disjoin" type="xsd:string"/>
       </xsd:choice>
    </xsd:sequence>
 </xsd:complexType>

 <xsd:complexType name="stringList">
    <xsd:sequence>
       <xsd:element name="string"
                    minOccurs="0"
                    maxOccurs="unbounded">
          <xsd:complexType>
             <xsd:attribute name="plan" type="xsd:string"/>
             <xsd:attribute name="package" type="xsd:string"/>
          </xsd:complexType>
       </xsd:element>
    </xsd:sequence>
 </xsd:complexType>

 <xsd:complexType name="changeStringList">
    <xsd:complexContent>
       <xsd:extension base="scr:stringList">
          <xsd:attribute name="importance" type="xsd:integer"/>
       </xsd:extension>
    </xsd:complexContent>
 </xsd:complexType>

 <xsd:complexType name="dump">
    <xsd:all>
       <xsd:element name="outputStrings"
                    minOccurs="0"
                    maxOccurs="1">
          <xsd:complexType>
             <xsd:attribute name="to" type="xsd:string"/>
          </xsd:complexType>
       </xsd:element>
       <xsd:element name="nodes"
                    minOccurs="0"
                    maxOccurs="1">
          <xsd:complexType>
             <xsd:attribute name="to" type="xsd:string"/>
          </xsd:complexType>
       </xsd:element>
    </xsd:all>
 </xsd:complexType>

</xsd:schema>

=== DOCGroup/ACE_TAO/branches/Telcordia_Diffserv/CIAO/DRM_RACE/Planners/ImportanceBinPacker/script.xml
<?xml version="1.0" encoding="utf-8"?>

<scr:script
 xmlns:scr="http://dtsn.darpa.mil/ixo/programs.asp?id=6#/DeploymentScript"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://dtsn.darpa.mil/ixo/programs.asp?id=6#/DeploymentScript
                     DeploymentScript.xsd">

   <shell>
   # Create a directory for test output

   mkdir -p test

   # Move old test results to an archive directory (bunch of goofy shell code here)

   test `ls test | wc -l` -gt 0 &amp;&amp; mkdir -p old_tests

   test `ls test | wc -l` -gt 0 &amp;&amp;                           \
        mkdir `ls old_tests | perl -pe 'BEGIN {print qq(test_0\n)}'  \
        | sed -e 's/test_//' | sort -n                               \
        | tail -1 | xargs -i expr {} + 1                             \
        | sed -e 's/^/old_tests\/test_/'`

   test `ls test | wc -l` -gt 0 &amp;&amp; (cd test ; tar -cO * ; rm -r * )  \
        | (cd `ls old_tests                                               \
        | sed -e 's/test_//' | sort -n                                    \
        | tail -1                                                         \
        | sed -e 's/^/old_tests\/test_/'` ;                               \
        tar xf - )
   </shell>

   <dump>
      <nodes to="test/nodes_0.dat"/>
   </dump>

   <!--
        Deploy Strings RT4H and RT5H together.  Then, deploy RT1H and show
        that the Importance Bin Packer automatically orders the teardown of
        RT5H in order to make room for higher-importance RT1H.
    -->

   <deploy>
      <string    plan="/opt/descriptors/Sample_Strings/descriptors/RT4H.cdp"
              package="/opt/descriptors/Sample_Strings/descriptors/RT4H.pcd"/>
      <string    plan="/opt/descriptors/Sample_Strings/descriptors/RT5H.cdp"
              package="/opt/descriptors/Sample_Strings/descriptors/RT5H.pcd"/>
   </deploy>

   <dump>
      <outputStrings to="test/output_strings_1"/>
      <nodes         to="test/nodes_1.dat"/>
   </dump>

   <deploy>
      <string    plan="/opt/descriptors/Sample_Strings/descriptors/RT1H.cdp"
              package="/opt/descriptors/Sample_Strings/descriptors/RT1H.pcd"/>
   </deploy>

   <dump>
      <outputStrings to="test/output_strings_2"/>
      <nodes         to="test/nodes_2.dat"/>
   </dump>

   <!--
        Clean up by tearing down RT1H and RT4H
    -->

   <teardown>
      <string    plan="/opt/descriptors/Sample_Strings/descriptors/RT1H.cdp"
              package="/opt/descriptors/Sample_Strings/descriptors/RT1H.pcd"/>
      <string    plan="/opt/descriptors/Sample_Strings/descriptors/RT4H.cdp"
              package="/opt/descriptors/Sample_Strings/descriptors/RT4H.pcd"/>
   </teardown>

   <dump>
      <outputStrings to="test/output_strings_3"/>
      <nodes         to="test/nodes_3.dat"/>
   </dump>

   <!--
        Repeat the test above, but increase the importance of
        RT5H after it's deployed.  The importance of RT5H will
        now be higher than the importance of RT1H when the
        latter is deployed.  This means that RT4H (instead of
        RT5H) will be town down to make room for RT1H.
    -->

   <deploy>
      <string    plan="/opt/descriptors/Sample_Strings/descriptors/RT4H.cdp"
              package="/opt/descriptors/Sample_Strings/descriptors/RT4H.pcd"/>
      <string    plan="/opt/descriptors/Sample_Strings/descriptors/RT5H.cdp"
              package="/opt/descriptors/Sample_Strings/descriptors/RT5H.pcd"/>
   </deploy>

   <change importance="6">
      <string    plan="/opt/descriptors/Sample_Strings/descriptors/RT5H.cdp"
              package="/opt/descriptors/Sample_Strings/descriptors/RT5H.pcd"/>
   </change>

   <dump>
      <outputStrings to="test/output_strings_4"/>
      <nodes         to="test/nodes_4.dat"/>
   </dump>

   <deploy>
      <string    plan="/opt/descriptors/Sample_Strings/descriptors/RT1H.cdp"
              package="/opt/descriptors/Sample_Strings/descriptors/RT1H.pcd"/>
   </deploy>

   <dump>
      <outputStrings to="test/output_strings_5"/>
      <nodes         to="test/nodes_5.dat"/>
   </dump>

   <!--
        Clean up by tearing down RT1H and RT5H.
    -->

   <teardown>
      <string    plan="/opt/descriptors/Sample_Strings/descriptors/RT1H.cdp"
              package="/opt/descriptors/Sample_Strings/descriptors/RT1H.pcd"/>
      <string    plan="/opt/descriptors/Sample_Strings/descriptors/RT5H.cdp"
              package="/opt/descriptors/Sample_Strings/descriptors/RT5H.pcd"/>
   </teardown>

   <dump>
      <outputStrings to="test/output_strings_6"/>
      <nodes         to="test/nodes_6.dat"/>
   </dump>

</scr:script>
