=== DOCGroup/ACE_TAO/tags/ACE+TAO+CIAO-5_7_2/CIAO/docs/schema/SANet_Network.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.vanderbilt.edu/SANet SANet_Network.xsd" xmlns:SANet="http://www.vanderbilt.edu/SANet"
  targetNamespace="http://www.vanderbilt.edu/SANet" elementFormDefault="qualified">
  <!-- Simple types. -->
  <xs:simpleType name="NodeID">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="1" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="PortID">
    <xs:restriction base="xs:string" />
  </xs:simpleType>
  <xs:simpleType name="TaskCost">
    <xs:restriction base="xs:double" />
  </xs:simpleType>
  <xs:simpleType name="CondUtil">
    <xs:restriction base="xs:double" />
  </xs:simpleType>
  <xs:simpleType name="CondKind">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ENVIRON" />
      <xs:enumeration value="SYSTEM" />
      <xs:enumeration value="DATA" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Probability">
    <xs:restriction base="xs:double">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value="1" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="LinkWeight">
    <xs:restriction base="xs:double">
      <xs:minInclusive value="-1" />
      <xs:maxInclusive value="1" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="MultFactor">
    <xs:restriction base="xs:double">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value="1" />
    </xs:restriction>
  </xs:simpleType>
  <!-- Complex types corresponding to IDL structures.
       (nodes, links, and network). -->
  <xs:complexType name="TaskNode">
    <xs:sequence>
      <xs:element name="nodeID" type="SANet:NodeID" />
      <xs:element name="name" type="xs:string" default="" />
      <xs:element name="priorProb" type="SANet:Probability" />
      <xs:element name="attenFactor" type="SANet:MultFactor" default="1" />
      <xs:element name="cost" type="SANet:TaskCost" default="0" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CondNode">
    <xs:sequence>
      <xs:element name="nodeID" type="SANet:NodeID" />
      <xs:element name="name" type="xs:string" default="" />
      <xs:element name="probTrue" type="SANet:Probability" default="0" />
      <xs:element name="utility" type="SANet:CondUtil" default="0" />
      <xs:element name="kind" type="SANet:CondKind" default="ENVIRON" />
      <xs:element name="attenFactor" type="SANet:MultFactor" default="1" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PrecondLink">
    <xs:sequence>
      <xs:element name="condID" type="SANet:NodeID" />
      <xs:element name="taskID" type="SANet:NodeID" />
      <xs:element name="portID" type="SANet:PortID" />
      <xs:element name="trueProb" type="SANet:Probability" />
      <xs:element name="falseProb" type="SANet:Probability" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="EffectLink">
    <xs:sequence>
      <xs:element name="taskID" type="SANet:NodeID" />
      <xs:element name="condID" type="SANet:NodeID" />
      <xs:element name="portID" type="SANet:PortID" />
      <xs:element name="weight" type="SANet:LinkWeight" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Network">
    <xs:sequence>
      <xs:element name="defaultAttenFactor" type="SANet:MultFactor" default="1" />
      <xs:element name="defaultTaskCost" type="SANet:TaskCost" default="0" />
      <xs:element name="defaultCondUtil" type="SANet:CondUtil" default="0" />
      <xs:element name="defaultCondProbTrue" type="SANet:Probability" default="0" />
      <xs:element name="linkThresh" type="SANet:LinkWeight" default="0" />
      <xs:element name="taskNode" type="SANet:TaskNode" maxOccurs="unbounded" />
      <xs:element name="condNode" type="SANet:CondNode" maxOccurs="unbounded" />
      <xs:element name="precondLink" type="SANet:PrecondLink" maxOccurs="unbounded" />
      <xs:element name="effectLink" type="SANet:EffectLink" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <!-- Top-level network element. -->
  <xs:element name="network" type="SANet:Network" />
</xs:schema>

=== DOCGroup/ACE_TAO/branches/RACE_devl/SA_POP/examples/Scheduling/sched_test1.san.xml
<?xml version="1.0" encoding="utf-8" ?>
<SANet:network xmlns:SANet="http://www.vanderbilt.edu/SANet" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.vanderbilt.edu/SANet SANet_Network.xsd" xmlns="http://www.vanderbilt.edu/SANet">
  <defaultAttenFactor />
  <defaultTaskCost />
  <defaultCondUtil />
  <defaultCondProbTrue />
  <linkThresh />
  <taskNode>
    <nodeID>2221</nodeID>
    <name>A1</name>
    <priorProb>1</priorProb>
    <attenFactor />
    <cost />
  </taskNode>
  <taskNode>
    <nodeID>2222</nodeID>
    <name>A2</name>
    <priorProb>1</priorProb>
    <attenFactor />
    <cost />
  </taskNode>
  <taskNode>
    <nodeID>2223</nodeID>
    <name>A3</name>
    <priorProb>0.4</priorProb>
    <attenFactor />
    <cost />
  </taskNode>
  <taskNode>
    <nodeID>2224</nodeID>
    <name>A4</name>
    <priorProb>1</priorProb>
    <attenFactor />
    <cost />
  </taskNode>
  <taskNode>
    <nodeID>2225</nodeID>
    <name>A5</name>
    <priorProb>0.4</priorProb>
    <attenFactor />
    <cost />
  </taskNode>
  <condNode>
    <nodeID>1111</nodeID>
    <name>C1</name>
    <probTrue>0</probTrue>
    <utility>0</utility>
    <kind>ENVIRON</kind>
    <attenFactor />
  </condNode>
  <condNode>
    <nodeID>1112</nodeID>
    <name>C2</name>
    <probTrue>0</probTrue>
    <utility>0</utility>
    <kind>SYSTEM</kind>
    <attenFactor />
  </condNode>
  <condNode>
    <nodeID>1113</nodeID>
    <name>C3</name>
    <probTrue>0</probTrue>
    <utility>0</utility>
    <kind>SYSTEM</kind>
    <attenFactor />
  </condNode>
  <condNode>
    <nodeID>1114</nodeID>
    <name>C4</name>
    <probTrue>0</probTrue>
    <utility>0</utility>
    <kind>ENVIRON</kind>
    <attenFactor />
  </condNode>
  <condNode>
    <nodeID>1115</nodeID>
    <name>C5</name>
    <probTrue>0</probTrue>
    <utility>10</utility>
    <kind>ENVIRON</kind>
    <attenFactor />
  </condNode>
  <precondLink>
    <condID>1111</condID>
    <taskID>2223</taskID>
    <portID>Port1In</portID>
    <trueProb>0.8</trueProb>
    <falseProb>0</falseProb>
  </precondLink>
  <precondLink>
    <condID>1112</condID>
    <taskID>2223</taskID>
    <portID>Port2In</portID>
    <trueProb>0.5</trueProb>
    <falseProb>0</falseProb>
  </precondLink>
  <precondLink>
    <condID>1114</condID>
    <taskID>2225</taskID>
    <portID>Port3In</portID>
    <trueProb>0.8</trueProb>
    <falseProb>0</falseProb>
  </precondLink>
  <precondLink>
    <condID>1113</condID>
    <taskID>2225</taskID>
    <portID>Port4In</portID>
    <trueProb>0.5</trueProb>
    <falseProb>0</falseProb>
  </precondLink>
  <effectLink>
    <taskID>2221</taskID>
    <condID>1111</condID>
    <portID>Port1Out</portID>
    <weight>1</weight>
  </effectLink>
  <effectLink>
    <taskID>2222</taskID>
    <condID>1112</condID>
    <portID>Port2Out</portID>
    <weight>1</weight>
  </effectLink>
  <effectLink>
    <taskID>2223</taskID>
    <condID>1113</condID>
    <portID>Port3Out</portID>
    <weight>1</weight>
  </effectLink>
  <effectLink>
    <taskID>2224</taskID>
    <condID>1114</condID>
    <portID>Port4Out</portID>
    <weight>1</weight>
  </effectLink>
  <effectLink>
    <taskID>2225</taskID>
    <condID>1115</condID>
    <portID>Port5Out</portID>
    <weight>1</weight>
  </effectLink>
</SANet:network>

=== DOCGroup/ACE_TAO/branches/SAPOP_Threat_dev/examples/Space/SPACE_Goal1.san.xml
<?xml version="1.0" encoding="utf-8" ?>
<SANet:network
  xmlns:SANet="http://www.vanderbilt.edu/SANet"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.vanderbilt.edu/SANet SANet_Network.xsd"
  xmlns="http://www.vanderbilt.edu/SANet">

  <defaultAttenFactor />
  <defaultTaskCost />
  <defaultCondUtil />
  <defaultCondProbTrue />
  <linkThresh />


  <taskNode>
    <nodeID>2221</nodeID>
    <name>Gizmo1</name>
    <priorProb>1.0</priorProb>
    <attenFactor />
    <cost />
  </taskNode>
  <taskNode>
    <nodeID>2222</nodeID>
    <name>Gizmo2</name>
    <priorProb>1.0</priorProb>
    <attenFactor />
    <cost />
  </taskNode>
  <taskNode>
    <nodeID>2223</nodeID>
    <name>Gizmo3</name>
    <priorProb>1.0</priorProb>
    <attenFactor />
    <cost />
  </taskNode>
  <taskNode>
    <nodeID>2231</nodeID>
    <name>Filter_G1</name>
    <priorProb>0.5</priorProb>
    <attenFactor />
    <cost />
  </taskNode>
  <taskNode>
    <nodeID>2232</nodeID>
    <name>Filter_G2_G3</name>
    <priorProb>0.25</priorProb>
    <attenFactor />
    <cost />
  </taskNode>
  <taskNode>
    <nodeID>2233</nodeID>
    <name>Compression_G1</name>
    <priorProb>0.5</priorProb>
    <attenFactor />
    <cost />
  </taskNode>
  <taskNode>
    <nodeID>2234</nodeID>
    <name>Compression_G2_G3</name>
    <priorProb>0.5</priorProb>
    <attenFactor />
    <cost />
  </taskNode>
  <taskNode>
    <nodeID>2235</nodeID>
    <name>Comm_Ex_G1</name>
    <priorProb>0.25</priorProb>
    <attenFactor />
    <cost />
  </taskNode>
  <taskNode>
    <nodeID>2236</nodeID>
    <name>Comm_Ex_G2_G3</name>
    <priorProb>0.25</priorProb>
    <attenFactor />
    <cost />
  </taskNode>
  <taskNode>
    <nodeID>2237</nodeID>
    <name>Exec</name>
    <priorProb>1.0</priorProb>
    <attenFactor />
    <cost />
  </taskNode>
  <taskNode>
    <nodeID>2241</nodeID>
    <name>Ground_G1</name>
    <priorProb>0.5</priorProb>
    <attenFactor />
    <cost />
  </taskNode>
  <taskNode>
    <nodeID>2242</nodeID>
    <name>Ground_G2_G3</name>
    <priorProb>0.5</priorProb>
    <attenFactor />
    <cost />
  </taskNode>




  <condNode>
    <nodeID>1121</nodeID>
    <name>Gizmo1_Data</name>
    <probTrue>0</probTrue>
    <utility>0</utility>
    <kind>DATA</kind>
    <attenFactor />
  </condNode>
  <condNode>
    <nodeID>1122</nodeID>
    <name>Gizmo2_Data</name>
    <probTrue>0</probTrue>
    <utility>0</utility>
    <kind>DATA</kind>
    <attenFactor />
  </condNode>
  <condNode>
    <nodeID>1123</nodeID>
    <name>Gizmo3_Data</name>
    <probTrue>0</probTrue>
    <utility>0</utility>
    <kind>DATA</kind>
    <attenFactor />
  </condNode>
  <condNode>
    <nodeID>1131</nodeID>
    <name>G1_Filter_Data</name>
    <probTrue>0</probTrue>
    <utility>0</utility>
    <kind>DATA</kind>
    <attenFactor />
  </condNode>
  <condNode>
    <nodeID>1132</nodeID>
    <name>G2_G3_Filter_Data</name>
    <probTrue>0</probTrue>
    <utility>0</utility>
    <kind>DATA</kind>
    <attenFactor />
  </condNode>
  <condNode>
    <nodeID>1133</nodeID>
    <name>G1_Comp_Data</name>
    <probTrue>0</probTrue>
    <utility>0</utility>
    <kind>DATA</kind>
    <attenFactor />
  </condNode>
  <condNode>
    <nodeID>1134</nodeID>
    <name>G2_G3_Comp_Data</name>
    <probTrue>0</probTrue>
    <utility>0</utility>
    <kind>DATA</kind>
    <attenFactor />
  </condNode>
  <condNode>
    <nodeID>1135</nodeID>
    <name>G1_Comm_Data</name>
    <probTrue>0</probTrue>
    <utility>0</utility>
    <kind>DATA</kind>
    <attenFactor />
  </condNode>
  <condNode>
    <nodeID>1136</nodeID>
    <name>G2_G3_Comm_Data</name>
    <probTrue>0</probTrue>
    <utility>0</utility>
    <kind>DATA</kind>
    <attenFactor />
  </condNode>
  <condNode>
    <nodeID>1137</nodeID>
    <name>Exec_Data</name>
    <probTrue>0</probTrue>
    <utility>0</utility>
    <kind>DATA</kind>
    <attenFactor />
  </condNode>
  <condNode>
    <nodeID>1141</nodeID>
    <name>G1_Data_Recvd</name>
    <probTrue>0</probTrue>
    <utility>10</utility>
    <kind />
    <attenFactor />
  </condNode>
  <condNode>
    <nodeID>1142</nodeID>
    <name>G2_G3_Data_Recvd</name>
    <probTrue>0</probTrue>
    <utility>0</utility>
    <kind />
    <attenFactor />
  </condNode>




  <precondLink>
    <condID>1121</condID>
    <taskID>2231</taskID>
    <portID>recv_data</portID>
    <trueProb>1.0</trueProb>
    <falseProb>0</falseProb>
  </precondLink>
  <precondLink>
    <condID>1122</condID>
    <taskID>2232</taskID>
    <portID>recv_data</portID>
    <trueProb>0.5</trueProb>
    <falseProb>0</falseProb>
  </precondLink>
  <precondLink>
    <condID>1123</condID>
    <taskID>2232</taskID>
    <portID>recv_data</portID>
    <trueProb>0.5</trueProb>
    <falseProb>0</falseProb>
  </precondLink>
  <precondLink>
    <condID>1131</condID>
    <taskID>2233</taskID>
    <portID>recv_data</portID>
    <trueProb>1.0</trueProb>
    <falseProb>0</falseProb>
  </precondLink>
  <precondLink>
    <condID>1132</condID>
    <taskID>2234</taskID>
    <portID>recv_data</portID>
    <trueProb>1.0</trueProb>
    <falseProb>0</falseProb>
  </precondLink>
  <precondLink>
    <condID>1133</condID>
    <taskID>2235</taskID>
    <portID>science_data</portID>
    <trueProb>0.5</trueProb>
    <falseProb>0</falseProb>
  </precondLink>
  <precondLink>
    <condID>1134</condID>
    <taskID>2236</taskID>
    <portID>science_data</portID>
    <trueProb>0.5</trueProb>
    <falseProb>0</falseProb>
  </precondLink>
  <precondLink>
    <condID>1137</condID>
    <taskID>2235</taskID>
    <portID>recv_command</portID>
    <trueProb>0.5</trueProb>
    <falseProb>0</falseProb>
  </precondLink>
  <precondLink>
    <condID>1137</condID>
    <taskID>2236</taskID>
    <portID>recv_command</portID>
    <trueProb>0.5</trueProb>
    <falseProb>0</falseProb>
  </precondLink>
  <precondLink>
    <condID>1135</condID>
    <taskID>2241</taskID>
    <portID>recv_transmission</portID>
    <trueProb>1.0</trueProb>
    <falseProb>0</falseProb>
  </precondLink>
  <precondLink>
    <condID>1136</condID>
    <taskID>2242</taskID>
    <portID>recv_transmission</portID>
    <trueProb>1.0</trueProb>
    <falseProb>0</falseProb>
  </precondLink>




  <effectLink>
    <taskID>2221</taskID>
    <condID>1121</condID>
    <portID>observation_data</portID>
    <weight>1.0</weight>
  </effectLink>
  <effectLink>
    <taskID>2222</taskID>
    <condID>1122</condID>
    <portID>observation_data</portID>
    <weight>1.0</weight>
  </effectLink>
  <effectLink>
    <taskID>2223</taskID>
    <condID>1123</condID>
    <portID>observation_data</portID>
    <weight>1.0</weight>
  </effectLink>
  <effectLink>
    <taskID>2231</taskID>
    <condID>1131</condID>
    <portID>send_data</portID>
    <weight>1.0</weight>
  </effectLink>
  <effectLink>
    <taskID>2232</taskID>
    <condID>1132</condID>
    <portID>send_data</portID>
    <weight>1.0</weight>
  </effectLink>
  <effectLink>
    <taskID>2233</taskID>
    <condID>1133</condID>
    <portID>send_data</portID>
    <weight>1.0</weight>
  </effectLink>
  <effectLink>
    <taskID>2234</taskID>
    <condID>1134</condID>
    <portID>send_data</portID>
    <weight>1.0</weight>
  </effectLink>
  <effectLink>
    <taskID>2235</taskID>
    <condID>1135</condID>
    <portID>transmit_data</portID>
    <weight>1.0</weight>
  </effectLink>
  <effectLink>
    <taskID>2236</taskID>
    <condID>1136</condID>
    <portID>transmit_data</portID>
    <weight>1.0</weight>
  </effectLink>
  <effectLink>
    <taskID>2237</taskID>
    <condID>1137</condID>
    <portID>send_command</portID>
    <weight>1.0</weight>
  </effectLink>
  <effectLink>
    <taskID>2241</taskID>
    <condID>1141</condID>
    <portID>NONE</portID>
    <weight>1.0</weight>
  </effectLink>
  <effectLink>
    <taskID>2242</taskID>
    <condID>1142</condID>
    <portID>NONE</portID>
    <weight>1.0</weight>
  </effectLink>

</SANet:network>
