=== DOCGroup/ACE_TAO/branches/Telcordia_Diffserv/DRM-repository/DRM_Services/BandwidthBroker/networkTopology.xsd
<!--Generated by XML Authority. Conforms to w3c http://www.w3.org/2001/XMLSchema-->
<xs:schema targetNamespace="www.darpa.mil/ARMS" 
	   xmlns:arms="www.darpa.mil/ARMS" 
	   xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	   elementFormDefault="qualified" attributeFormDefault="unqualified">
<!--$Id$-->
  <!-- include types used by config files -->
  <xs:include schemaLocation="arms_common_defs.xsd"/>

  <!-- Updated: 
       March 2, 2003, 
       March 23, 04 (bpo) added arms namespace
       Oct 27, 2004 added changes to HostSUbnet , QoSClass + made changes to 
	completly populate the db rom this input - Kirthika
  -->
  <xs:annotation>
    <xs:documentation>
      schema for the ARMS network topology: routers/switches and their
      interconnection.  The relationship between hosts and the edge
      routers that serve them are also defined.
    </xs:documentation>
    <xs:documentation>
      See p. 19, Section 3.2.1.1.2, Network Resource Specifications
      Dynamic Resource Management Functional Capability Document For
      the U.S. Navy, Sept. 2003.
      
    </xs:documentation>
    <xs:documentation>
      Usage: An instance of the file will be read in by the Telcordia
      network resource management software, the Bandwidth Broker.
      This reading in this network configuration information does not
      exclude future network disovery during initialization/operations
    </xs:documentation>
  </xs:annotation>
  
  <!-- Note: The default for maxOccurs and minOccurs is 1.  If
       minOccurs is not specified, there must be at least one of the
       element.  If maxOccurs is not specified, there must be at most
       one of the element. -->

  <!-- ********************************************************
       switch: both for L2 switch or L3 router
       ******************************************************* -->
  <xs:complexType name = "switch">
    <!-- QUESTION: 23 Mar 04: Do we need to add security attributes to
         each switch? -->
    <xs:annotation>
      <xs:documentation>
	If L3 capable flag is set, it is a Layer 3 router or it is a
	Layer 2 switch isItEdge is a flag to determine whether it is
	an edge router/switch or core router/switch managedElemenI is
	a fully qualified DNS name for the router/switch so as to to
	able to talk to the switch/router by the flowProvisioner; in
	the future, it could be the EMS that manages the switch/router
	user ID, password, enble pasword are for logging into the
	router/switch for configuring and enabling (new) switch
	configuration and for doing privilege operations on the
	router/switch
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element ref = "arms:isL3Capable"/>
      <xs:element ref = "arms:isItEdge"/>
      <xs:element ref = "arms:internalID"/>
      <xs:element ref = "arms:managedElementID"/>
      <xs:element ref = "arms:userID"/>
      <xs:element ref = "arms:password"/>
      <xs:element ref = "arms:enPassword"/>
      <xs:element ref = "arms:physicalLocation" minOccurs="0"/> 
      <xs:element ref = "arms:switchID" minOccurs="0"> 
	<xs:annotation>
	  <xs:documentation>
	    SwitchID is the manufacturer's ID (Serial No.?) for
	    inventory purposes
	  </xs:documentation>
	</xs:annotation>
      </xs:element>
      <xs:element ref = "arms:switchType" minOccurs="0"/> 
      <xs:element ref = "arms:operatingSystem" minOccurs="0"/> 
    </xs:sequence>
  </xs:complexType>

  <!-- ******************************************************** 
       switch list:        
       type A network configuration has one or more 
       switches/routers
       ******************************************************* -->
  <xs:complexType name = "switchList">
    <xs:sequence maxOccurs = "unbounded">
      <xs:element ref = "arms:switch"/>
    </xs:sequence>
  </xs:complexType>


  
	  
  <!-- ******************************************************** 
       L3 Interface
       ******************************************************* -->
  <xs:complexType name = "L3Interface">
    <xs:sequence>
      <xs:element ref = "arms:internalID">
	<xs:annotation>
	  <xs:documentation>
	    internalID is internal ID of the interface 
	  </xs:documentation>
	</xs:annotation>
      </xs:element>
      <xs:element ref = "arms:routerInternalID">
	<xs:annotation>
	  <xs:documentation>
	    routerInternalID relates this Interface to the router it
	    belongs to
	  </xs:documentation>
	</xs:annotation>
      </xs:element>
      <xs:element ref = "arms:interfaceID">
	<xs:annotation>
	  <xs:documentation>
	    interfaceID is either of the form technology/slot/port or
	    technology chassis/slot/port
	  </xs:documentation>
	</xs:annotation>
      </xs:element>
      <xs:element ref = "arms:IPAddress"/>
      <xs:element ref = "arms:IPSubnetMask"/>
      <xs:element ref = "arms:bandwidthOutbitspersec"/>
      <xs:element ref = "arms:bandwidthInbitspersec"/>
      <xs:element ref = "arms:isItEdge"/>
      </xs:sequence>
   </xs:complexType>
  
  <!-- ******************************************************** 
       L3 InterfaceList A router has one or more (L3) interfaces
       ******************************************************* -->
  <xs:complexType name = "L3InterfaceList">
    <xs:sequence maxOccurs = "unbounded" minOccurs="0">
      <xs:element ref = "arms:L3Interface"/>
    </xs:sequence>
  </xs:complexType>
  
  <!-- ******************************************************** 
       L2 Interface
       ******************************************************* -->
  <xs:complexType name = "L2Interface">
    <xs:annotation>
      <xs:documentation>
	A L2 interface can belong to several VLANS; list them
	separated by comma.
	Remote side interface info for this L2
	interface; no easy way to deduce the remote interface for L2
	interfaces!
      </xs:documentation>
    </xs:annotation>

    <xs:sequence>
      <xs:element ref = "arms:internalID">
	<xs:annotation>
	  <xs:documentation>
	    internalID is internal ID of the interface 
	  </xs:documentation>
	</xs:annotation>
      </xs:element>
      <xs:element ref = "arms:switchInternalID">
	<xs:annotation>
	  <xs:documentation>
	    switchInternalID relates this Interface to the switch it
	    belongs to
	  </xs:documentation>
	</xs:annotation>
      </xs:element>
      <xs:element ref = "arms:portID">
	<xs:annotation>
	  <xs:documentation>
	    portID is either of the form technology/slot/port or
	    technology chassis/slot/port
	  </xs:documentation>
	</xs:annotation>
      </xs:element>
      <xs:element ref = "arms:L2Address"/> 
      <xs:element ref = "arms:vlanIDs"/>
      <xs:element ref = "arms:bandwidthOutbitspersec"/>
      <xs:element ref = "arms:bandwidthInbitspersec"/>
      <xs:element ref = "arms:remoteInterfaceInternalID" minOccurs="0"/>
      <xs:element ref = "arms:remoteSwitchRouterInternalID" minOccurs="0"/>
      <xs:element ref = "arms:isRemoteL2">
      <xs:annotation>
	  <xs:documentation>
	    IsRemoteL2 is a flag to tell whether the remote side
	    connected to an L2 switch!
	  </xs:documentation>
	</xs:annotation>
      </xs:element>

    </xs:sequence>
  </xs:complexType>

  
  <!-- ******************************************************** 
       L2 InterfaceList 
       A switch has one or more L2 interfaces
       ******************************************************* -->
  <xs:complexType name = "L2InterfaceList">
    <xs:sequence maxOccurs = "unbounded" minOccurs="0">
      <xs:element ref = "arms:L2Interface" />
    </xs:sequence>
  </xs:complexType>
  
  <!-- ******************************************************** 
       HostSubnet    
       Hosts and their subnet,pool,edge
       interface info
       ******************************************************* -->
  <xs:complexType name = "HostSubnet">
    <xs:sequence>
      <xs:element ref = "arms:internalID"/>
      <xs:element ref = "arms:subnetAddress"/>
      <xs:element ref = "arms:IPSubnetMask"/>
      <xs:element ref = "arms:hostName" minOccurs="0"/>
      <xs:element ref = "arms:edgeRouterInterfaceInternalID" minOccurs="0">
	<xs:annotation>
	  <xs:documentation>
	    internalID of the connected L3 interface
	  </xs:documentation>
	</xs:annotation>
      </xs:element>
      <xs:element ref = "arms:edgeRouterinterfaceIPaddress" minOccurs="0"/>
      <xs:element ref = "arms:edgeL2SwitchInterfaceInternalID" minOccurs="0">
	<xs:annotation>
	  <xs:documentation>
	    internalID of the L2 switch connected  
	  </xs:documentation>
	</xs:annotation>
      </xs:element>	
      <xs:element ref = "arms:poolName"/>	
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name = "HostSubnetList">
    <xs:sequence maxOccurs = "unbounded" minOccurs="0">
      <xs:element ref = "arms:HostSubnet"/> 
    </xs:sequence>
  </xs:complexType>

<!-- ******************************************************** 
       QoSClass list:        
       capacity allocated for use for each type of QoS class
       ******************************************************* -->
  <xs:complexType name = "QoSClassList">
    <xs:sequence maxOccurs = "unbounded">
      <xs:element ref = "arms:QoSClass"/>
    </xs:sequence>
  </xs:complexType>

 <!-- ******************************************************** 
       QoSClass
       ******************************************************* -->
  <xs:complexType name = "QoSClass">
    <xs:sequence>
      <xs:element ref = "arms:internalID">
	<xs:annotation>
	  <xs:documentation>
	    internalID is internal ID of the class capacity 
	  </xs:documentation>
	</xs:annotation>
      </xs:element>
      <xs:element ref = "arms:QoSClassName">
	<xs:annotation>
	  <xs:documentation>
	    The class of service 
	  </xs:documentation>
	</xs:annotation>
      </xs:element>
      <xs:element ref = "arms:totalCapacityAllowed">
	<xs:annotation>
	  <xs:documentation>
	    total bandwidth percentage allowed for the service class
	  </xs:documentation>
	</xs:annotation>
      </xs:element>
      <xs:element ref = "arms:DSCP">
	<xs:annotation>
	  <xs:documentation>
	    DifServ codepoint for the service class
	  </xs:documentation>
	</xs:annotation>
      </xs:element>
      <xs:element ref = "arms:dropPrecedence">
	<xs:annotation>
	  <xs:documentation>
	    DifServ drop precedence for the service class
	  </xs:documentation>
	</xs:annotation>
      </xs:element>
     </xs:sequence>
  </xs:complexType>


  <!-- ******************************************************** 
       network topology
       ******************************************************* -->
  <xs:complexType name = "networkTopology">
    <xs:sequence>
      <xs:element ref = "arms:topologyName"/>
      <xs:element ref = "arms:switchList"/>
      <xs:element ref = "arms:L3InterfaceList"/> 
      <xs:element ref = "arms:L2InterfaceList"/>
      <xs:element ref = "arms:HostSubnetList"/>
      <xs:element ref = "arms:QoSClassList"/>		
    </xs:sequence>
  </xs:complexType>



  <!-- ******************************************************** 
       foundation elements
       ******************************************************* -->
  <xs:element name = "IPAddress" type = "xs:string"/>
  <xs:element name = "IPSubnetMask" type = "xs:string"/>
  <xs:element name = "L2Address" type = "xs:string"/>
  <xs:element name = "L3Interface" type = "arms:L3Interface"/>
  <xs:element name = "L2Interface" type = "arms:L2Interface"/>
  <xs:element name = "QoSClass" type = "arms:QoSClass"/>
  <xs:element name = "QoSClassList" type = "arms:QoSClassList"/>
  <xs:element name = "L2InterfaceList" type = "arms:L2InterfaceList"/>
  <xs:element name = "L3InterfaceList" type = "arms:L3InterfaceList"/>
  <xs:element name = "QoSClassName" type = "xs:string"/>
  <xs:element name = "totalCapacityAllowed" type = "xs:nonNegativeInteger"/>
  <xs:element name = "bandwidthInbitspersec" type = "xs:nonNegativeInteger"/>
  <xs:element name = "bandwidthOutbitspersec" type = "xs:nonNegativeInteger"/>
  <xs:element name = "DSCP" type = "xs:nonNegativeInteger"/>
  <xs:element name = "dropPrecedence" type = "xs:nonNegativeInteger"/>
  <xs:element name = "edgeRouterInterfaceInternalID" type = "xs:string"/>
  <xs:element name = "edgeL2SwitchInterfaceInternalID" type = "xs:string"/>
  <xs:element name = "edgeRouterinterfaceIPaddress" type = "xs:string"/>
  <xs:element name = "enPassword" type = "xs:string"/>
  <xs:element name = "interfaceID" type = "xs:string"/>
  <xs:element name = "poolName" type = "xs:string"/>
  <xs:element name = "hostName" type = "xs:string"/>
  <xs:element name = "internalID" type = "xs:string"/>
  <xs:element name = "isItEdge" type = "xs:boolean"/>
  <xs:element name = "isL3Capable" type = "xs:boolean"/>
  <xs:element name = "isRemoteL2" type = "xs:boolean"/>
  <xs:element name = "managedElementID" type = "xs:string"/>
  <xs:element name = "networkTopology" type = "arms:networkTopology"/>
  <xs:element name = "password" type = "xs:string"/>
  <xs:element name = "physicalLocation" type = "xs:string"/>
  <xs:element name = "portID" type = "xs:string"/>
  <xs:element name = "remoteInterfaceInternalID" type = "xs:string"/>
  <xs:element name = "remoteSwitchRouterInternalID" type = "xs:string"/>
  <xs:element name = "routerInternalID" type = "xs:string"/>
  <xs:element name = "subnetAddress" type = "xs:string"/>
  <xs:element name = "HostSubnet" type = "arms:HostSubnet"/>
  <xs:element name = "HostSubnetList" type = "arms:HostSubnetList"/>
  <xs:element name = "switch" type = "arms:switch"/>
  <xs:element name = "switchID" type = "xs:string"/>
  <xs:element name = "switchInternalID" type = "xs:string"/>
  <xs:element name = "switchList" type = "arms:switchList"/>
  <xs:element name = "switchType" type = "xs:string"/>
  <xs:element name = "topologyName" type = "xs:string"/>
  <xs:element name = "userID" type = "xs:string"/>
  <xs:element name = "vlanIDs" type = "xs:string"/>

</xs:schema>

=== DOCGroup/ACE_TAO/branches/Telcordia_Diffserv/DRM-repository/DRM_Services/BandwidthBroker/src/nw_topo_lab.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!--$Id$-->
<!-- Name: networkTopologyLab.xml, Network Topology Sample File -->

<!-- Date: Updated: April 13, 2004 -->

<!-- Purpose:  This file defines (an instance of) the network toplogy (for the ARMS OEP): routers/switches and their interconnection. The relationship between hosts and edge routers are also defined -->

<!-- See  p. 19, Section 3.2.1.1.2, 3.2.1.1.2, 	Network Resource Specifications
Dynamic Resource Management Functional Capability Document For the U.S. Navy, Sept. 2003   -->

<!-- Usage:  This file will be read in by the Telcordia network resource management software, 
the Bandwidth Broker.  This reading in this network configuration information does not exclude future network disovery  during initialization/operations -->

<arms:networkTopology xmlns:arms="www.darpa.mil/ARMS" 
		      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		      xsi:schemaLocation="www.darpa.mil/ARMS networkTopology.xsd">

  <arms:topologyName>ARMSOEPToplogy </arms:topologyName>
  <arms:switchList>

    <!-- ==================================================
	 A network configuration has one or more switches/routers
	 ================================================== -->

    <!-- A switch can be a Layer2 Switch or Layer 3 Router -->
    <arms:switch>
      <!-- If L3 capable, it is a router or it is a Layer 2 switch -->
      <arms:isL3Capable>true</arms:isL3Capable>  
      
      <!-- is it an edge router/switch? -->
      <arms:isItEdge>true</arms:isItEdge>     

      <!-- internalID of the switch/router -->
      <arms:internalID>LA</arms:internalID>    
      <!--managedElement is a fully qualified DNS name for the
           router/switch so as to to able to talk to the switch/router
           by the flowProvisioner; -->
      <arms:managedElementID>192.4.20.67</arms:managedElementID>         
      
      <!-- user ID, password, enble pasword are for logging into the
           router/swtich for configuring and enabling new switch
           configuration and doing privilege operations -->
      
      <arms:userID>armsuser1</arms:userID>
      <arms:password>lessprivPassword</arms:password>
      <arms:enPassword>privPassword</arms:enPassword>
      <arms:physicalLocation>leap frog lab</arms:physicalLocation>
      <arms:switchID>manufacturerID1</arms:switchID>
      <arms:switchType>Cisco 3620</arms:switchType>
      <arms:operatingSystem>
	<arms:name>IOS</arms:name>
	<arms:version>12.0</arms:version>
      </arms:operatingSystem>
    </arms:switch>

    <arms:switch>                       
      <!--A L3 router -->
      <arms:isL3Capable>true</arms:isL3Capable>
      <arms:isItEdge>true</arms:isItEdge>
      <arms:internalID>BOS</arms:internalID>                   
      <arms:managedElementID>192.4.20.78</arms:managedElementID>                        
      <arms:userID>armsuser001</arms:userID>
      <arms:password>lessPrivPassword</arms:password>
      <arms:enPassword>privPassword</arms:enPassword>
      <arms:switchID>manfacturerID2</arms:switchID>
      <arms:switchType>Cisco 3620</arms:switchType>
      <arms:operatingSystem>
	<arms:name>IOS</arms:name>
	<arms:version>12.0</arms:version>
      </arms:operatingSystem>
    </arms:switch> 	  
  

  <arms:switch>                       
      <!--A L3 router -->
      <arms:isL3Capable>true</arms:isL3Capable>
      <arms:isItEdge>true</arms:isItEdge>
      <arms:internalID>DC</arms:internalID>                   
      <arms:managedElementID>192.4.20.79</arms:managedElementID>                        
      <arms:userID>armsuser001</arms:userID>
      <arms:password>lessPrivPassword</arms:password>
      <arms:enPassword>privPassword</arms:enPassword>
      <arms:switchID>manfacturerID2</arms:switchID>
      <arms:switchType>Cisco 3620</arms:switchType>
      <arms:operatingSystem>
	<arms:name>IOS</arms:name>
	<arms:version>12.0</arms:version>
      </arms:operatingSystem>
    </arms:switch> 	  
  </arms:switchList>

  
  <arms:L3InterfaceList>   
    <!-- List all the interfaces of all the L3 routers  -->
    
    <arms:L3Interface>                       
      <!-- internalID of the interface -->
      <arms:internalID>interface001</arms:internalID>     
      
      <!-- routerInternalID relates this Interface to the router it
           belongs to -->
      <arms:routerInternalID>LA</arms:routerInternalID>     
      
      <!-- interfaceID is either of the form technology/slot/port or
           technology chassis/slot/port -->
      <arms:interfaceID>Ethernet1/0</arms:interfaceID>
      <arms:IPAddress>172.16.15.2</arms:IPAddress>
      <arms:IPSubnetMask>255.255.255.0</arms:IPSubnetMask>
      <arms:bandwidthOutbitspersec>10000</arms:bandwidthOutbitspersec>
      <arms:bandwidthInbitspersec>10000</arms:bandwidthInbitspersec>       
    </arms:L3Interface>

    <arms:L3Interface>        
      <arms:internalID>interface002</arms:internalID>                              
      <arms:routerInternalID>LA</arms:routerInternalID>
      <arms:interfaceID>Ethernet1/1</arms:interfaceID>
      <arms:IPAddress>172.16.14.1</arms:IPAddress>
      <arms:IPSubnetMask>255.255.255.0</arms:IPSubnetMask>
      <arms:bandwidthOutbitspersec>10000</arms:bandwidthOutbitspersec>
      <arms:bandwidthInbitspersec>10000</arms:bandwidthInbitspersec>       
    </arms:L3Interface>

    <arms:L3Interface>        
      <arms:internalID>interface003</arms:internalID>                              
      <arms:routerInternalID>BOS</arms:routerInternalID>
      <arms:interfaceID>Ethernet1/1</arms:interfaceID>
      <arms:IPAddress>172.16.15.1</arms:IPAddress>
      <arms:IPSubnetMask>255.255.255.0</arms:IPSubnetMask>
      <arms:bandwidthOutbitspersec>10000</arms:bandwidthOutbitspersec>
      <arms:bandwidthInbitspersec>10000</arms:bandwidthInbitspersec>       
    </arms:L3Interface>
  
    <arms:L3Interface>        
      <arms:internalID>interface004</arms:internalID>                              
      <arms:routerInternalID>BOS</arms:routerInternalID>
      <arms:interfaceID>Ethernet1/2</arms:interfaceID>
      <arms:IPAddress>172.16.13.1</arms:IPAddress>
      <arms:IPSubnetMask>255.255.255.0</arms:IPSubnetMask>
      <arms:bandwidthOutbitspersec>10000</arms:bandwidthOutbitspersec>
      <arms:bandwidthInbitspersec>10000</arms:bandwidthInbitspersec>       
    </arms:L3Interface>
  
    <arms:L3Interface>        
      <arms:internalID>interface005</arms:internalID>                              
      <arms:routerInternalID>DC</arms:routerInternalID>
      <arms:interfaceID>Ethernet1/0</arms:interfaceID>
      <arms:IPAddress>172.16.15.3</arms:IPAddress>
      <arms:IPSubnetMask>255.255.255.0</arms:IPSubnetMask>
      <arms:bandwidthOutbitspersec>10000</arms:bandwidthOutbitspersec>
      <arms:bandwidthInbitspersec>10000</arms:bandwidthInbitspersec>       
    </arms:L3Interface>

  </arms:L3InterfaceList>
  
   <arms:L2InterfaceList>
   </arms:L2InterfaceList>
    
  <arms:subnetToEdgeInterfaceList>               
    <!-- ==================================================
	 subnetToEdgeInterface 
	 For every subnet containing hosts, the edge router side
	 interface info
	 ================================================== -->
    <arms:subnetToEdgeInterface>
      <arms:internalID>subnet011</arms:internalID>
      <arms:subnetAddress>172.16.14.0</arms:subnetAddress>
      <arms:IPSubnetMask>255.255.255.0</arms:IPSubnetMask>
      <arms:bandwidthOutbitspersec>100000</arms:bandwidthOutbitspersec>
      <arms:bandwidthInbitspersec>100000</arms:bandwidthInbitspersec>
      <arms:edgeRouterInterfaceID>LA</arms:edgeRouterInterfaceID> 
      <arms:edgeRouterinterfaceIPaddress>172.16.14.1</arms:edgeRouterinterfaceIPaddress> 
    </arms:subnetToEdgeInterface> 

    <arms:subnetToEdgeInterface> 
      <arms:internalID>subnet021</arms:internalID>
      <arms:subnetAddress>172.16.13.0</arms:subnetAddress>
      <arms:IPSubnetMask>255.255.255.0</arms:IPSubnetMask>
      <arms:bandwidthOutbitspersec>100000</arms:bandwidthOutbitspersec>
      <arms:bandwidthInbitspersec>100000</arms:bandwidthInbitspersec>
      <arms:edgeRouterInterfaceID>BOS</arms:edgeRouterInterfaceID> 
      <arms:edgeRouterinterfaceIPaddress>172.16.13.1</arms:edgeRouterinterfaceIPaddress> 
    </arms:subnetToEdgeInterface> 
  </arms:subnetToEdgeInterfaceList>
</arms:networkTopology>
