=== DOCGroup/ACE_TAO/branches/Telcordia_Diffserv/CoSMIC/PSM/CCM/PICML2Cadena/paradigms/cadena_scenario/cadena_scenario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<?udm interface="cadena_scenario" version="1.00"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!-- generated on Mon Nov 15 23:59:43 2004 -->

 <xsd:complexType name="ESSConnectionType">
			<xsd:sequence>
				<xsd:element name="Property" type="PropertyType" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
  <xsd:attribute name="ConnectorID" type="xsd:string" use="required"/>
  <xsd:attribute name="sources" type="xsd:IDREFS"/>
  <xsd:attribute name="sinks" type="xsd:IDREFS"/>
  <xsd:attribute name="_id" type="xsd:ID"/>
  <xsd:attribute name="_archetype" type="xsd:IDREF"/>
  <xsd:attribute name="_derived" type="xsd:IDREFS"/>
  <xsd:attribute name="_instances" type="xsd:IDREFS"/>
  <xsd:attribute name="_desynched_atts" type="xsd:string"/>
  <xsd:attribute name="_real_archetype" type="xsd:boolean"/>
  <xsd:attribute name="_subtype" type="xsd:boolean"/>
 </xsd:complexType>

 <xsd:complexType name="ScenariosType">
			<xsd:sequence>
				<xsd:element name="Scenario" type="ScenarioType" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
  <xsd:attribute name="_id" type="xsd:ID"/>
  <xsd:attribute name="_archetype" type="xsd:IDREF"/>
  <xsd:attribute name="_derived" type="xsd:IDREFS"/>
  <xsd:attribute name="_instances" type="xsd:IDREFS"/>
  <xsd:attribute name="_desynched_atts" type="xsd:string"/>
  <xsd:attribute name="_real_archetype" type="xsd:boolean"/>
  <xsd:attribute name="_subtype" type="xsd:boolean"/>
 </xsd:complexType>

 <xsd:complexType name="FRConnectionType">
			<xsd:sequence>
				<xsd:element name="Property" type="PropertyType" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
  <xsd:attribute name="facets_end_" type="xsd:IDREF"/>
  <xsd:attribute name="receptacles_end_" type="xsd:IDREF"/>
  <xsd:attribute name="_id" type="xsd:ID"/>
  <xsd:attribute name="_archetype" type="xsd:IDREF"/>
  <xsd:attribute name="_derived" type="xsd:IDREFS"/>
  <xsd:attribute name="_instances" type="xsd:IDREFS"/>
  <xsd:attribute name="_desynched_atts" type="xsd:string"/>
  <xsd:attribute name="_real_archetype" type="xsd:boolean"/>
  <xsd:attribute name="_subtype" type="xsd:boolean"/>
 </xsd:complexType>

 <xsd:complexType name="EventSinkType">
  <xsd:attribute name="name" type="xsd:string" use="required"/>
  <xsd:attribute name="sourcesConnections" type="xsd:IDREFS"/>
  <xsd:attribute name="_id" type="xsd:ID"/>
  <xsd:attribute name="_archetype" type="xsd:IDREF"/>
  <xsd:attribute name="_derived" type="xsd:IDREFS"/>
  <xsd:attribute name="_instances" type="xsd:IDREFS"/>
  <xsd:attribute name="_desynched_atts" type="xsd:string"/>
  <xsd:attribute name="_real_archetype" type="xsd:boolean"/>
  <xsd:attribute name="_subtype" type="xsd:boolean"/>
 </xsd:complexType>

 <xsd:complexType name="EventSourceType">
  <xsd:attribute name="name" type="xsd:string" use="required"/>
  <xsd:attribute name="sinksConnections" type="xsd:IDREFS"/>
  <xsd:attribute name="_id" type="xsd:ID"/>
  <xsd:attribute name="_archetype" type="xsd:IDREF"/>
  <xsd:attribute name="_derived" type="xsd:IDREFS"/>
  <xsd:attribute name="_instances" type="xsd:IDREFS"/>
  <xsd:attribute name="_desynched_atts" type="xsd:string"/>
  <xsd:attribute name="_real_archetype" type="xsd:boolean"/>
  <xsd:attribute name="_subtype" type="xsd:boolean"/>
 </xsd:complexType>

 <xsd:complexType name="ReceptacleType">
  <xsd:attribute name="name" type="xsd:string" use="required"/>
  <xsd:attribute name="facets" type="xsd:IDREFS"/>
  <xsd:attribute name="_id" type="xsd:ID"/>
  <xsd:attribute name="_archetype" type="xsd:IDREF"/>
  <xsd:attribute name="_derived" type="xsd:IDREFS"/>
  <xsd:attribute name="_instances" type="xsd:IDREFS"/>
  <xsd:attribute name="_desynched_atts" type="xsd:string"/>
  <xsd:attribute name="_real_archetype" type="xsd:boolean"/>
  <xsd:attribute name="_subtype" type="xsd:boolean"/>
 </xsd:complexType>

 <xsd:complexType name="FacetType">
  <xsd:attribute name="name" type="xsd:string" use="required"/>
  <xsd:attribute name="receptacles" type="xsd:IDREFS"/>
  <xsd:attribute name="_id" type="xsd:ID"/>
  <xsd:attribute name="_archetype" type="xsd:IDREF"/>
  <xsd:attribute name="_derived" type="xsd:IDREFS"/>
  <xsd:attribute name="_instances" type="xsd:IDREFS"/>
  <xsd:attribute name="_desynched_atts" type="xsd:string"/>
  <xsd:attribute name="_real_archetype" type="xsd:boolean"/>
  <xsd:attribute name="_subtype" type="xsd:boolean"/>
 </xsd:complexType>

 <xsd:complexType name="PropertyType">
  <xsd:attribute name="value" type="xsd:string" use="required"/>
  <xsd:attribute name="name" type="xsd:string" use="required"/>
  <xsd:attribute name="type" type="xsd:string" use="required"/>
  <xsd:attribute name="_id" type="xsd:ID"/>
  <xsd:attribute name="_archetype" type="xsd:IDREF"/>
  <xsd:attribute name="_derived" type="xsd:IDREFS"/>
  <xsd:attribute name="_instances" type="xsd:IDREFS"/>
  <xsd:attribute name="_desynched_atts" type="xsd:string"/>
  <xsd:attribute name="_real_archetype" type="xsd:boolean"/>
  <xsd:attribute name="_subtype" type="xsd:boolean"/>
 </xsd:complexType>

 <xsd:complexType name="ComponentInstanceType">
			<xsd:sequence>
				<xsd:element name="EventSink" type="EventSinkType" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="EventSource" type="EventSourceType" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="Facet" type="FacetType" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="Property" type="PropertyType" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="Receptacle" type="ReceptacleType" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
  <xsd:attribute name="type" type="xsd:string" use="required"/>
  <xsd:attribute name="name" type="xsd:string" use="required"/>
  <xsd:attribute name="_id" type="xsd:ID"/>
  <xsd:attribute name="_archetype" type="xsd:IDREF"/>
  <xsd:attribute name="_derived" type="xsd:IDREFS"/>
  <xsd:attribute name="_instances" type="xsd:IDREFS"/>
  <xsd:attribute name="_desynched_atts" type="xsd:string"/>
  <xsd:attribute name="_real_archetype" type="xsd:boolean"/>
  <xsd:attribute name="_subtype" type="xsd:boolean"/>
 </xsd:complexType>

 <xsd:complexType name="ScenarioType">
			<xsd:sequence>
				<xsd:element name="ComponentInstance" type="ComponentInstanceType" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="ESSConnection" type="ESSConnectionType" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="FRConnection" type="FRConnectionType" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="Property" type="PropertyType" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
  <xsd:attribute name="_id" type="xsd:ID"/>
  <xsd:attribute name="_archetype" type="xsd:IDREF"/>
  <xsd:attribute name="_derived" type="xsd:IDREFS"/>
  <xsd:attribute name="_instances" type="xsd:IDREFS"/>
  <xsd:attribute name="_desynched_atts" type="xsd:string"/>
  <xsd:attribute name="_real_archetype" type="xsd:boolean"/>
  <xsd:attribute name="_subtype" type="xsd:boolean"/>
 </xsd:complexType>

 <xsd:element name="Scenarios" type="ScenariosType"/>

</xsd:schema>

=== DOCGroup/ACE_TAO/branches/Telcordia_Diffserv/CoSMIC/PSM/CCM/PICML2Cadena/Transformations/examples/RobotAssembly_OriginalVersion/exported.xml
<Scenarios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Udm\cadena_scenario.xsd">
	<Scenario>
		<ComponentInstance name="HumanMachineInterface" type="RobotAssembly/HumanMachineInterface">
			<EventSink _id="id2215" name="WorkDisplayUpdate" sourcesConnections="id2216"/>
			<Facet name="Controller"/>
			<Receptacle _id="id222a" name="HumanResponse" facets="id222b"/>
		</ComponentInstance>
		<ComponentInstance name="ManagementWorkInstructions" type="RobotAssembly/ManagementWorkInstructions">
			<EventSink _id="id2219" name="ProductionReport" sourcesConnections="id221a"/>
			<EventSource _id="id2217" name="sendWorkOrder" sinksConnections="id2218"/>
			<Facet name="Controller"/>
		</ComponentInstance>
		<ComponentInstance name="WatchSettingManager" type="RobotAssembly/WatchSettingManager">
			<EventSink _id="id2221" name="ProcessingStatus" sourcesConnections="id2222"/>
			<EventSink _id="id2223" name="PalletStatus" sourcesConnections="id2224"/>
			<EventSink _id="id2225" name="recvWorkOrder" sourcesConnections="id2218"/>
			<EventSource _id="id221b" name="Display" sinksConnections="id2216"/>
			<EventSource _id="id221c" name="ProductionControl" sinksConnections="id221d"/>
			<EventSource _id="id221e" name="MovePallet" sinksConnections="id221f"/>
			<EventSource _id="id2220" name="ProductionReport" sinksConnections="id221a"/>
			<Facet _id="id222c" name="DisplayResponse" receptacles="id222b"/>
		</ComponentInstance>
		<ComponentInstance name="PalletConveyorManager" type="RobotAssembly/PalletConveyorManager">
			<EventSink _id="id2227" name="PalletRequests" sourcesConnections="id221f"/>
			<EventSource _id="id2226" name="PalletStatus" sinksConnections="id2224"/>
			<Facet name="Controller"/>
		</ComponentInstance>
		<ComponentInstance name="RobotManager" type="RobotAssembly/RobotManager">
			<EventSink _id="id2229" name="ProcessPalletCommands" sourcesConnections="id221d"/>
			<EventSource _id="id2228" name="ProcessingStatus" sinksConnections="id2222"/>
			<Facet name="Controller"/>
		</ComponentInstance>
		<ESSConnection _id="id2218" sinks="id2225" sources="id2217" ConnectorID="emit"/>
		<ESSConnection _id="id2216" sinks="id2215" sources="id221b" ConnectorID="emit"/>
		<ESSConnection _id="id221d" sinks="id2229" sources="id221c" ConnectorID="emit"/>
		<ESSConnection _id="id221f" sinks="id2227" sources="id221e" ConnectorID="emit"/>
		<ESSConnection _id="id221a" sinks="id2219" sources="id2220" ConnectorID="emit"/>
		<ESSConnection _id="id2224" sinks="id2223" sources="id2226" ConnectorID="emit"/>
		<ESSConnection _id="id2222" sinks="id2221" sources="id2228" ConnectorID="emit"/>
		<FRConnection _id="id222b" facets_end_="id222c" receptacles_end_="id222a"/>
		<Property name="PICML_pathname" type="STRING" value="/RobotAssemblyImplementations/RobotAssemblyImplementation/RobotAssembly"/>
	</Scenario>
</Scenarios>
